heat_template_version: 2015-04-30

description: Example template to deploy a PAN firewall and Linux server instances

parameters:
  pan_image:
    type: string
    label: PAN image name
    description: PAN virtual firewall image to be used for firewall instance
    default: PA-VM-KVM-8.1.0

  server_image:
    type: string
    label: Server image name
    description: Server image to be used for server instance
    default: Ubuntu-14.04

  pan_flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used for PAN firewall instance
    default: m1.medium

  server_flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used for server instance
    default: m1.small

  server_key:
    type: string
    label: Key name
    description: Name of key-pair to be used for server instance

  mgmt_network:
    type: string
    label: Management network name
    description: Network to attach management interface of PAN firewall instance to.

resources:
  pan_trust_net:
    type: OS::Neutron::Net
    properties:
      name: pan_trust_net

  pan_trust_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: pan_trust_net }
      cidr: 192.168.100.0/24
      gateway_ip: 192.168.100.10
      dns_nameservers: [8.8.8.8]
      name: pan_trust_subnet

  pan_untrust_net:
    type: OS::Neutron::Net
    properties:
      name: pan_untrust_net

  pan_untrust_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: pan_untrust_net }
      cidr: 192.168.200.0/24
      gateway_ip: 192.168.200.10
      dns_nameservers: [8.8.8.8]
      name: pan_untrust_subnet

  allow_ssh_https_icmp_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22
          port_range_max: 22
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 443
          port_range_max: 443
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0

  allow_any:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: udp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0

  pan_untrust_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: pan_untrust_net }
      security_groups:
        - { get_resource: allow_any }
      fixed_ips:
        - subnet: { get_resource: pan_untrust_subnet }
          ip_address: "192.168.200.10"

  pan_trust_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: pan_trust_net }
      security_groups:
        - { get_resource: allow_any }
      fixed_ips:
        - subnet: { get_resource: pan_trust_subnet }
          ip_address: "192.168.100.10"

  pan_fw_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: pan_image }
      flavor: { get_param: pan_flavor }
      networks:
        - network: { get_param: mgmt_network }
        - port: { get_resource: pan_trust_port }
        - port: { get_resource: pan_untrust_port }
      user_data_format: RAW
      config_drive: true
      personality:
        /config/init-cfg.txt: {get_file: "/home/npatel/internal_fw/config/init-cfg.txt"}
        /config/bootstrap.xml: {get_file: "/home/npatel/internal_fw/config/bootstrap.xml"}
        /license/authcodes: {get_file: "/home/npatel/internal_fw/license/authcodes"}

  server_trust:
    type: OS::Nova::Server
    properties:
      image: { get_param: server_image }
      flavor: { get_param: server_flavor }
      key_name: { get_param: server_key }
      security_groups:
        - { get_resource: allow_any }
      networks:
        - network: { get_resource: pan_trust_net }

  server_untrust:
    type: OS::Nova::Server
    properties:
      image: { get_param: server_image }
      flavor: { get_param: server_flavor }
      key_name: { get_param: server_key }
      security_groups:
        - { get_resource: allow_any }
      networks:
        - network: { get_resource: pan_untrust_net }

outputs:
  pan_fw_name:
    description: Name of the PAN firewall
    value: { get_attr: [pan_fw_instance, name] }

  pan_fw_mgmt_ip:
    description: Management IP address of the PAN firewall
    value: { get_attr: [pan_fw_instance, networks, external, 0 ] }

  server_trust_ip:
    description: IP of the server on trust network
    value: { get_attr: [ server_trust, first_address ] }

  server_untrust_ip:
    description: IP of the server on the untrust network
    value: { get_attr: [ server_untrust, first_address ] }

